name: Build and Push .NET App using GitHub actions

on:
  [workflow_dispatch]

jobs:
  publish-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      