name: Build and Push .NET App using GitHub actions

on:
  [workflow_dispatch]

jobs:
  publish-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
        
      - name: Log into Docker Hub
        uses: docker/login-action@v2

        -name: Publish to container image
        run: dotnet publish -c Release -o ./publish

      