name: Build and Push .NET App using GitHub actions

on:
  [workflow_dispatch]

jobs:
  publish-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Build docker image
        run: |
          docker build -t lakshanjay/webapplication1:1.6 .
        
      - name: Push docker image
        run: |
          docker push lakshanjay/webapplication1:1.6

      
