name: Build and Push .NET App using GitHub actions

on:
  [workflow_dispatch]

jobs:
  publish-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
         
      - name: Log in to Docker Hub
        run: |
          docker login -u lakshanjay -p ${{ secrets.DOCKER_HUB_TOKEN }}
        
      - name: Build docker image
        run: |
          docker build -t lakshanjay/webapplication1:1.5 .
        
      - name: Show build images
        run: |
          docker images
      - name: Show running containers
        run: |
          docker ps -a

      - name: Push docker image
        run: |
          docker push lakshanjay/webapplication1:1.5

      
